server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: leasing-decision-core

  liquibase:
    enabled: false

  datasource:
    url: ${DB_URL:jdbc:mariadb://10.208.198.79:3307/vapor}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

    hikari:
      read-only: true
      minimum-idle: ${DB_POOL_MIN_IDLE:1}
      maximum-pool-size: ${DB_POOL_MAX_SIZE:5}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:10000}
      validation-timeout: ${DB_VALIDATION_TIMEOUT:5000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true

  packages-to-scan:
    - ro.bcrleasing.leasingdecisioncore.blacklist.api

  paths-to-match:
    - /api/v1/blacklist/**


decision-core:
  capabilities:
    sibcor:
      mode: ${SIBCOR_MODE:real}
      base-url: ${SIBCOR_BASE_URL:https://sibcor-bcr-leasing-gateway-bcr-sibcor-staging.apps.ostst.bcr.os/api/v1/bcrleasing/}
      blacklist-path: ${SIBCOR_BLACKLIST_PATH:blacklist}
      auth-base-url: ${SIBCOR_AUTH_BASE_URL:https://authuatlb.bcr.wan/authserver/oauth/token}
      auth-client-id: ${SIBCOR_AUTH_CLIENT_ID:BcrLeasing}
      auth-grant-type: ${SIBCOR_AUTH_GRANT_TYPE:client_credentials}
      auth-username: ${SIBCOR_AUTH_USERNAME}
      auth-password: ${SIBCOR_AUTH_PASSWORD}

      connect-timeout: ${SIBCOR_CONNECT_TIMEOUT:5s}
      read-timeout: ${SIBCOR_READ_TIMEOUT:30s}
      token-refresh-before-expiry: ${SIBCOR_TOKEN_REFRESH_BEFORE_EXPIRY:5m}
      fallback-token-ttl: ${SIBCOR_FALLBACK_TOKEN_TTL:50m}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always